def load_dic_grade():
	dic_grade = [
		{'ano':1,'semestre':1,'modalidade':'C','dia':'seg','hora_begin':8,'hora_end':10,'x':0,'y':8,'disciplina':'Cálc. Dif. e Integral I','status':'nan'},
		{'ano':1,'semestre':1,'modalidade':'C','dia':'seg','hora_begin':10,'hora_end':12,'x':0,'y':10,'disciplina':'Geom. Analítica Plana','status':'nan'},
		{'ano':2,'semestre':1,'modalidade':'C','dia':'seg','hora_begin':16,'hora_end':18,'x':0,'y':16,'disciplina':'Estruturas Algébricas I','status':'nan'},
		{'ano':2,'semestre':1,'modalidade':'C','dia':'seg','hora_begin':14,'hora_end':16,'x':0,'y':14,'disciplina':'Geom. Euclidiana Espacial','status':'nan'},
		{'ano':3,'semestre':1,'modalidade':'C','dia':'seg','hora_begin':8,'hora_end':10,'x':1,'y':8,'disciplina':'Análise Matemática I','status':'nan'},
		{'ano':3,'semestre':1,'modalidade':'B','dia':'seg','hora_begin':14,'hora_end':16,'x':1,'y':14,'disciplina':'Espaços Métricos','status':'nan'},
		{'ano':3,'semestre':1,'modalidade':'L','dia':'seg','hora_begin':10,'hora_end':12,'x':1,'y':10,'disciplina':'História e Sociologia da Educação: Questões da Educação Matemática','status':'nan'},
		{'ano':3,'semestre':1,'modalidade':'L','dia':'seg','hora_begin':14,'hora_end':16,'x':2,'y':14,'disciplina':'Prática de Ensino e Estágio Supervisionado I','status':'nan'},
		{'ano':3,'semestre':1,'modalidade':'B','dia':'seg','hora_begin':10,'hora_end':12,'x':2,'y':10,'disciplina':'Teo. dos Números','status':'nan'},
		{'ano':4,'semestre':1,'modalidade':'L','dia':'seg','hora_begin':14,'hora_end':16,'x':3,'y':14,'disciplina':'Espaços Métricos','status':'nan'},
		{'ano':4,'semestre':1,'modalidade':'C','dia':'seg','hora_begin':16,'hora_end':18,'x':1,'y':16,'disciplina':'Funções de Variável Complexa I','status':'nan'},
		{'ano':4,'semestre':1,'modalidade':'B','dia':'seg','hora_begin':10,'hora_end':12,'x':3,'y':10,'disciplina':'Métodos Matemáticos para Física','status':'nan'},
		{'ano':4,'semestre':1,'modalidade':'L','dia':'seg','hora_begin':10,'hora_end':12,'x':4,'y':10,'disciplina':'Teo. dos Números','status':'nan'},
		{'ano':1,'semestre':1,'modalidade':'C','dia':'ter','hora_begin':10,'hora_end':12,'x':0,'y':10,'disciplina':'Funções Elementares','status':'nan'},
		{'ano':1,'semestre':1,'modalidade':'C','dia':'ter','hora_begin':8,'hora_end':10,'x':0,'y':8,'disciplina':'Geom. Analítica Plana','status':'nan'},
		{'ano':2,'semestre':1,'modalidade':'L','dia':'ter','hora_begin':16,'hora_end':18,'x':0,'y':16,'disciplina':'Filosofia da Educação: questões da Educação Matemática','status':'nan'},
		{'ano':2,'semestre':1,'modalidade':'C','dia':'ter','hora_begin':10,'hora_end':12,'x':1,'y':10,'disciplina':'Física Geral II','status':'nan'},
		{'ano':2,'semestre':1,'modalidade':'C','dia':'ter','hora_begin':14,'hora_end':16,'x':0,'y':14,'disciplina':'Álgebra Linear I','status':'nan'},
		{'ano':3,'semestre':1,'modalidade':'L','dia':'ter','hora_begin':10,'hora_end':12,'x':2,'y':10,'disciplina':'História e Sociologia da Educação: Questões da Educação Matemática','status':'nan'},
		{'ano':3,'semestre':1,'modalidade':'C','dia':'ter','hora_begin':8,'hora_end':10,'x':1,'y':8,'disciplina':'Probabilidade','status':'nan'},
		{'ano':3,'semestre':1,'modalidade':'L','dia':'ter','hora_begin':14,'hora_end':18,'x':1,'y':14,'disciplina':'Psicologia do Desenvolvimento','status':'nan'},
		{'ano':4,'semestre':1,'modalidade':'B','dia':'ter','hora_begin':14,'hora_end':16,'x':2,'y':14,'disciplina':'Análise Matemática III','status':'nan'},
		{'ano':4,'semestre':1,'modalidade':'C','dia':'ter','hora_begin':10,'hora_end':12,'x':3,'y':10,'disciplina':'Funções de Variável Complexa I','status':'nan'},
		{'ano':4,'semestre':1,'modalidade':'B','dia':'ter','hora_begin':16,'hora_end':18,'x':2,'y':16,'disciplina':'Teo. da Medida e Integração','status':'nan'},
		{'ano':1,'semestre':1,'modalidade':'C','dia':'qua','hora_begin':8,'hora_end':10,'x':0,'y':8,'disciplina':'Cálc. Dif. e Integral I','status':'nan'},
		{'ano':1,'semestre':1,'modalidade':'C','dia':'qua','hora_begin':10,'hora_end':12,'x':0,'y':10,'disciplina':'Matemática Elementar','status':'nan'},
		{'ano':2,'semestre':1,'modalidade':'C','dia':'qua','hora_begin':14,'hora_end':16,'x':0,'y':14,'disciplina':'Cálc. Dif. e Integral III','status':'nan'},
		{'ano':2,'semestre':1,'modalidade':'C','dia':'qua','hora_begin':10,'hora_end':12,'x':1,'y':10,'disciplina':'Equações de Diferenças','status':'nan'},
		{'ano':2,'semestre':1,'modalidade':'C','dia':'qua','hora_begin':16,'hora_end':18,'x':0,'y':16,'disciplina':'Estruturas Algébricas I','status':'nan'},
		{'ano':3,'semestre':1,'modalidade':'C','dia':'qua','hora_begin':10,'hora_end':12,'x':2,'y':10,'disciplina':'Análise Matemática I','status':'nan'},
		{'ano':3,'semestre':1,'modalidade':'B','dia':'qua','hora_begin':8,'hora_end':10,'x':1,'y':8,'disciplina':'Espaços Métricos','status':'nan'},
		{'ano':4,'semestre':1,'modalidade':'B','dia':'qua','hora_begin':16,'hora_end':18,'x':1,'y':16,'disciplina':'Análise Matemática III','status':'nan'},
		{'ano':4,'semestre':1,'modalidade':'L','dia':'qua','hora_begin':8,'hora_end':10,'x':2,'y':8,'disciplina':'Espaços Métricos','status':'nan'},
		{'ano':4,'semestre':1,'modalidade':'B','dia':'qua','hora_begin':14,'hora_end':16,'x':1,'y':14,'disciplina':'Métodos Matemáticos para Física','status':'nan'},
		{'ano':4,'semestre':1,'modalidade':'L','dia':'qua','hora_begin':14,'hora_end':16,'x':2,'y':14,'disciplina':'Prática de Ensino e Estágio Supervisionado III','status':'nan'},
		{'ano':4,'semestre':1,'modalidade':'L','dia':'qua','hora_begin':18,'hora_end':19,'x':0,'y':18,'disciplina':'Prática de Ensino e Estágio Supervisionado III','status':'nan'},
		{'ano':1,'semestre':1,'modalidade':'C','dia':'qui','hora_begin':10,'hora_end':12,'x':0,'y':10,'disciplina':'Funções Elementares','status':'nan'},
		{'ano':2,'semestre':1,'modalidade':'L','dia':'qui','hora_begin':8,'hora_end':10,'x':0,'y':8,'disciplina':'Filosofia da Educação: questões da Educação Matemática','status':'nan'},
		{'ano':2,'semestre':1,'modalidade':'C','dia':'qui','hora_begin':10,'hora_end':12,'x':1,'y':10,'disciplina':'Física Geral II','status':'nan'},
		{'ano':2,'semestre':1,'modalidade':'C','dia':'qui','hora_begin':14,'hora_end':16,'x':0,'y':14,'disciplina':'Geom. Euclidiana Espacial','status':'nan'},
		{'ano':3,'semestre':1,'modalidade':'C','dia':'qui','hora_begin':8,'hora_end':10,'x':1,'y':8,'disciplina':'Análise Matemática I','status':'nan'},
		{'ano':3,'semestre':1,'modalidade':'L','dia':'qui','hora_begin':14,'hora_end':18,'x':1,'y':14,'disciplina':'Didática I','status':'nan'},
		{'ano':3,'semestre':1,'modalidade':'C','dia':'qui','hora_begin':10,'hora_end':12,'x':2,'y':10,'disciplina':'Probabilidade','status':'nan'},
		{'ano':3,'semestre':1,'modalidade':'B','dia':'qui','hora_begin':16,'hora_end':18,'x':0,'y':16,'disciplina':'Teo. dos Grupos','status':'nan'},
		{'ano':3,'semestre':1,'modalidade':'B','dia':'qui','hora_begin':14,'hora_end':16,'x':2,'y':14,'disciplina':'Teo. dos Números','status':'nan'},
		{'ano':4,'semestre':1,'modalidade':'L','dia':'qui','hora_begin':16,'hora_end':18,'x':2,'y':16,'disciplina':'Resolução de Problemas na Educação Básica - optativa','status':'nan'},
		{'ano':4,'semestre':1,'modalidade':'L','dia':'qui','hora_begin':14,'hora_end':16,'x':3,'y':14,'disciplina':'Teo. dos Números','status':'nan'},
		{'ano':1,'semestre':1,'modalidade':'C','dia':'sex','hora_begin':8,'hora_end':10,'x':0,'y':8,'disciplina':'Cálc. Dif. e Integral I','status':'nan'},
		{'ano':1,'semestre':1,'modalidade':'C','dia':'sex','hora_begin':10,'hora_end':12,'x':0,'y':10,'disciplina':'Matemática Elementar','status':'nan'},
		{'ano':2,'semestre':1,'modalidade':'C','dia':'sex','hora_begin':8,'hora_end':10,'x':1,'y':8,'disciplina':'Cálc. Dif. e Integral III','status':'nan'},
		{'ano':2,'semestre':1,'modalidade':'C','dia':'sex','hora_begin':10,'hora_end':12,'x':1,'y':10,'disciplina':'Equações de Diferenças','status':'nan'},
		{'ano':2,'semestre':1,'modalidade':'C','dia':'sex','hora_begin':14,'hora_end':16,'x':0,'y':14,'disciplina':'Álgebra Linear I','status':'nan'},
		{'ano':3,'semestre':1,'modalidade':'L','dia':'sex','hora_begin':14,'hora_end':18,'x':1,'y':14,'disciplina':'Prática de Ensino e Estágio Supervisionado I','status':'nan'},
		{'ano':3,'semestre':1,'modalidade':'B','dia':'sex','hora_begin':10,'hora_end':12,'x':2,'y':10,'disciplina':'Teo. dos Grupos','status':'nan'},
		{'ano':4,'semestre':1,'modalidade':'L','dia':'sex','hora_begin':8,'hora_end':12,'x':3,'y':8,'disciplina':'Prática de Ensino e Estágio Supervisionado III','status':'nan'},
		{'ano':4,'semestre':1,'modalidade':'L','dia':'sex','hora_begin':16,'hora_end':18,'x':0,'y':16,'disciplina':'Resolução de Problemas na Educação Básica - optativa','status':'nan'},
		{'ano':4,'semestre':1,'modalidade':'B','dia':'sex','hora_begin':14,'hora_end':16,'x':2,'y':14,'disciplina':'Teo. da Medida e Integração','status':'nan'},
		{'ano':1,'semestre':1,'modalidade':'C','dia':'sab','hora_begin':14,'hora_end':18,'x':0,'y':14,'disciplina':'Libras, Educação Especial e Inclusiva','status':'nan'},
		{'ano':1,'semestre':2,'modalidade':'C','dia':'seg','hora_begin':8,'hora_end':10,'x':0,'y':8,'disciplina':'Cálc. Dif. e Integral II','status':'nan'},
		{'ano':1,'semestre':2,'modalidade':'C','dia':'seg','hora_begin':14,'hora_end':16,'x':0,'y':14,'disciplina':'Educação Financeira numa perspectiva crítica','status':'nan'},
		{'ano':1,'semestre':2,'modalidade':'C','dia':'seg','hora_begin':10,'hora_end':12,'x':0,'y':10,'disciplina':'Geom. Analítica Espacial','status':'nan'},
		{'ano':2,'semestre':2,'modalidade':'C','dia':'seg','hora_begin':14,'hora_end':16,'x':1,'y':14,'disciplina':'Cálc. Dif. e Integral IV','status':'nan'},
		{'ano':2,'semestre':2,'modalidade':'C','dia':'seg','hora_begin':16,'hora_end':18,'x':0,'y':16,'disciplina':'Estruturas Algébricas II','status':'nan'},
		{'ano':2,'semestre':2,'modalidade':'B','dia':'seg','hora_begin':10,'hora_end':12,'x':1,'y':10,'disciplina':'Álgebra Linear II','status':'nan'},
		{'ano':3,'semestre':2,'modalidade':'B','dia':'seg','hora_begin':8,'hora_end':10,'x':1,'y':8,'disciplina':'Análise Matemática II','status':'nan'},
		{'ano':3,'semestre':2,'modalidade':'C','dia':'seg','hora_begin':10,'hora_end':12,'x':2,'y':10,'disciplina':'Equações Diferenciais Ordinárias','status':'nan'},
		{'ano':3,'semestre':2,'modalidade':'L','dia':'seg','hora_begin':8,'hora_end':10,'x':2,'y':8,'disciplina':'Prática de Ensino e Estágio Supervisionado II','status':'nan'},
		{'ano':4,'semestre':2,'modalidade':'B','dia':'seg','hora_begin':14,'hora_end':16,'x':2,'y':14,'disciplina':'Funções de Variável Complexa II','status':'nan'},
		{'ano':4,'semestre':2,'modalidade':'L','dia':'seg','hora_begin':14,'hora_end':16,'x':3,'y':14,'disciplina':'História da Matemática','status':'nan'},
		{'ano':4,'semestre':2,'modalidade':'L','dia':'seg','hora_begin':16,'hora_end':18,'x':1,'y':16,'disciplina':'Matemática Elementar do Ponto de Vista Avançado','status':'nan'},
		{'ano':4,'semestre':2,'modalidade':'L','dia':'seg','hora_begin':10,'hora_end':12,'x':3,'y':10,'disciplina':'Modelagem Matemática para a Educação Básica - optativa','status':'nan'},
		{'ano':4,'semestre':2,'modalidade':'L','dia':'seg','hora_begin':18,'hora_end':19,'x':0,'y':18,'disciplina':'Prática de Ensino e Estágio Supervisionado IV','status':'nan'},
		{'ano':4,'semestre':2,'modalidade':'B','dia':'seg','hora_begin':16,'hora_end':18,'x':2,'y':16,'disciplina':'Teo. dos Corpos','status':'nan'},
		{'ano':1,'semestre':2,'modalidade':'C','dia':'ter','hora_begin':8,'hora_end':10,'x':0,'y':8,'disciplina':'Física Geral I','status':'nan'},
		{'ano':1,'semestre':2,'modalidade':'C','dia':'ter','hora_begin':10,'hora_end':12,'x':0,'y':10,'disciplina':'Geom. Euclidiana Plana','status':'nan'},
		{'ano':2,'semestre':2,'modalidade':'C','dia':'ter','hora_begin':10,'hora_end':12,'x':1,'y':10,'disciplina':'Física Geral III','status':'nan'},
		{'ano':2,'semestre':2,'modalidade':'L','dia':'ter','hora_begin':14,'hora_end':18,'x':0,'y':14,'disciplina':'Política Educacional Brasileira','status':'nan'},
		{'ano':3,'semestre':2,'modalidade':'L','dia':'ter','hora_begin':14,'hora_end':18,'x':1,'y':14,'disciplina':'Didática II','status':'nan'},
		{'ano':3,'semestre':2,'modalidade':'B','dia':'ter','hora_begin':8,'hora_end':10,'x':1,'y':8,'disciplina':'Geom. Diferencial','status':'nan'},
		{'ano':3,'semestre':2,'modalidade':'L','dia':'ter','hora_begin':8,'hora_end':12,'x':2,'y':8,'disciplina':'Matemática da Educação Básica','status':'nan'},
		{'ano':4,'semestre':2,'modalidade':'B','dia':'ter','hora_begin':16,'hora_end':18,'x':2,'y':16,'disciplina':'Análise Funcional','status':'nan'},
		{'ano':4,'semestre':2,'modalidade':'L','dia':'ter','hora_begin':10,'hora_end':12,'x':3,'y':10,'disciplina':'Modelagem Matemática para a Educação Básica - optativa','status':'nan'},
		{'ano':4,'semestre':2,'modalidade':'L','dia':'ter','hora_begin':8,'hora_end':10,'x':3,'y':8,'disciplina':'Prática de Ensino e Estágio Supervisionado IV','status':'nan'},
		{'ano':4,'semestre':2,'modalidade':'L','dia':'ter','hora_begin':14,'hora_end':18,'x':3,'y':14,'disciplina':'Tecnologia no Ensino de Matemática','status':'nan'},
		{'ano':4,'semestre':2,'modalidade':'B','dia':'ter','hora_begin':14,'hora_end':16,'x':2,'y':14,'disciplina':'Teo. dos Corpos','status':'nan'},
		{'ano':1,'semestre':2,'modalidade':'C','dia':'qua','hora_begin':8,'hora_end':10,'x':0,'y':8,'disciplina':'Cálc. Dif. e Integral II','status':'nan'},
		{'ano':1,'semestre':2,'modalidade':'C','dia':'qua','hora_begin':10,'hora_end':12,'x':0,'y':10,'disciplina':'Educação Financeira numa perspectiva crítica','status':'nan'},
		{'ano':2,'semestre':2,'modalidade':'C','dia':'qua','hora_begin':14,'hora_end':16,'x':0,'y':14,'disciplina':'Cálc. Dif. e Integral IV','status':'nan'},
		{'ano':2,'semestre':2,'modalidade':'C','dia':'qua','hora_begin':10,'hora_end':12,'x':1,'y':10,'disciplina':'Desenho Geométrico e Geom. Descritiva','status':'nan'},
		{'ano':2,'semestre':2,'modalidade':'C','dia':'qua','hora_begin':16,'hora_end':18,'x':0,'y':16,'disciplina':'Estruturas Algébricas II','status':'nan'},
		{'ano':3,'semestre':2,'modalidade':'B','dia':'qua','hora_begin':8,'hora_end':10,'x':1,'y':8,'disciplina':'Espaços Topológicos','status':'nan'},
		{'ano':3,'semestre':2,'modalidade':'L','dia':'qua','hora_begin':8,'hora_end':12,'x':2,'y':8,'disciplina':'Psicologia da Aprendizagem','status':'nan'},
		{'ano':4,'semestre':2,'modalidade':'B','dia':'qua','hora_begin':10,'hora_end':12,'x':3,'y':10,'disciplina':'Análise Funcional','status':'nan'},
		{'ano':4,'semestre':2,'modalidade':'B','dia':'qua','hora_begin':14,'hora_end':16,'x':1,'y':14,'disciplina':'Funções de Variável Complexa II','status':'nan'},
		{'ano':4,'semestre':2,'modalidade':'L','dia':'qua','hora_begin':14,'hora_end':16,'x':2,'y':14,'disciplina':'História da Matemática','status':'nan'},
		{'ano':4,'semestre':2,'modalidade':'L','dia':'qua','hora_begin':16,'hora_end':18,'x':1,'y':16,'disciplina':'Matemática Elementar do Ponto de Vista Avançado','status':'nan'},
		{'ano':4,'semestre':2,'modalidade':'B','dia':'qua','hora_begin':16,'hora_end':18,'x':2,'y':16,'disciplina':'Teo. dos Conjuntos','status':'nan'},
		{'ano':1,'semestre':2,'modalidade':'C','dia':'qui','hora_begin':8,'hora_end':10,'x':0,'y':8,'disciplina':'Geom. Analítica Espacial','status':'nan'},
		{'ano':1,'semestre':2,'modalidade':'C','dia':'qui','hora_begin':10,'hora_end':12,'x':0,'y':10,'disciplina':'Geom. Euclidiana Plana','status':'nan'},
		{'ano':2,'semestre':2,'modalidade':'C','dia':'qui','hora_begin':16,'hora_end':18,'x':0,'y':16,'disciplina':'Cálculo Numérico','status':'nan'},
		{'ano':2,'semestre':2,'modalidade':'C','dia':'qui','hora_begin':14,'hora_end':16,'x':0,'y':14,'disciplina':'Desenho Geométrico e Geom. Descritiva','status':'nan'},
		{'ano':2,'semestre':2,'modalidade':'C','dia':'qui','hora_begin':10,'hora_end':12,'x':1,'y':10,'disciplina':'Física Geral III','status':'nan'},
		{'ano':3,'semestre':2,'modalidade':'C','dia':'qui','hora_begin':8,'hora_end':10,'x':1,'y':8,'disciplina':'Equações Diferenciais Ordinárias','status':'nan'},
		{'ano':3,'semestre':2,'modalidade':'C','dia':'qui','hora_begin':10,'hora_end':12,'x':2,'y':10,'disciplina':'Estatística','status':'nan'},
		{'ano':3,'semestre':2,'modalidade':'L','dia':'qui','hora_begin':14,'hora_end':19,'x':1,'y':14,'disciplina':'Prática de Ensino e Estágio Supervisionado II','status':'nan'},
		{'ano':4,'semestre':2,'modalidade':'B','dia':'qui','hora_begin':14,'hora_end':16,'x':2,'y':14,'disciplina':'Teo. dos Conjuntos','status':'nan'},
		{'ano':1,'semestre':2,'modalidade':'C','dia':'sex','hora_begin':8,'hora_end':10,'x':0,'y':8,'disciplina':'Cálc. Dif. e Integral II','status':'nan'},
		{'ano':1,'semestre':2,'modalidade':'C','dia':'sex','hora_begin':10,'hora_end':12,'x':0,'y':10,'disciplina':'Física Geral I','status':'nan'},
		{'ano':1,'semestre':2,'modalidade':'C','dia':'sex','hora_begin':14,'hora_end':18,'x':0,'y':14,'disciplina':'Introdução à Ciência da Computação','status':'nan'},
		{'ano':2,'semestre':2,'modalidade':'C','dia':'sex','hora_begin':14,'hora_end':16,'x':1,'y':14,'disciplina':'Cálculo Numérico','status':'nan'},
		{'ano':2,'semestre':2,'modalidade':'B','dia':'sex','hora_begin':16,'hora_end':18,'x':1,'y':16,'disciplina':'Álgebra Linear II','status':'nan'},
		{'ano':3,'semestre':2,'modalidade':'B','dia':'sex','hora_begin':16,'hora_end':18,'x':2,'y':16,'disciplina':'Análise Matemática II','status':'nan'},
		{'ano':3,'semestre':2,'modalidade':'B','dia':'sex','hora_begin':8,'hora_end':10,'x':1,'y':8,'disciplina':'Espaços Topológicos','status':'nan'},
		{'ano':3,'semestre':2,'modalidade':'C','dia':'sex','hora_begin':14,'hora_end':16,'x':2,'y':14,'disciplina':'Estatística','status':'nan'},
		{'ano':3,'semestre':2,'modalidade':'B','dia':'sex','hora_begin':10,'hora_end':12,'x':1,'y':10,'disciplina':'Geom. Diferencial','status':'nan'},
		{'ano':4,'semestre':2,'modalidade':'L','dia':'sex','hora_begin':8,'hora_end':12,'x':2,'y':8,'disciplina':'Prática de Ensino e Estágio Supervisionado IV','status':'nan'},
	]
	return dic_grade
